version: 2.1

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      
      - setup_remote_docker

      - run:
          name: Install make
          command: |
            apk add --no-cache make

      - run:
          name: Build container
          command: |
            make build

      - run:
          name: Push container
          command: |
            if [[ ! -z "$CIRCLE_TAG" ]]
            then
              docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
              make release
            else
              echo "There is no tag, skipping..."
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: docker-cloud
          filters:
            tags:
              only: /.*/
